version: '3'

services:
  app:
    build: ../
    command: python -m markdown_embed_code
    volumes:
      - ../:/
    environment:
      - INPUT_OUTPUT=readme.md
      - INPUT_TOKEN=xxx
      - GITHUB_REPOSITORY=markdown-embed-code
      - GITHUB_EVENT_PATH=https://github.com/technology-studio/markdown-embed-code/pull/6